services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./environments/.env
    depends_on:
      - database
      - minio

  database:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=run2learn_app
      - MYSQL_ROOT_PASSWORD=ForaTemer0
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "my-mysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: my-minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: chavedeacesso
      MINIO_SECRET_KEY: supersecretchave
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  minio_data:
    driver: local
